### ISSUE TITLE
Behavior of editops 

### ISSUE THREAD

**Issue by hongduosun** [maxbachmann/rapidfuzz#176]
Hi,  thanks for writing RapidFuzz, the performance is so impressive and I'm using it in my project. But I find certain editops behavior is quite different to other similar functions.

Currently the `delete` opration in `levenshtein_editops` would select the leftmost one if there are multiple choices, see the example below:
```
> levenshtein_editops("GGTAAAA","NNGGTAA")
[('insert', 0, 0), ('insert', 0, 1), ('delete', 3, 5), ('delete', 4, 5)]
```
The first `AA` was deleted rather than the latter two `A`s.

Other packages would delete the rightmost two `A`s since `GGAA` is the longest common substring in a row.

`difflib.SequenceMatcher` would give:
```
SequenceMatcher(a="GGTAAAA",b="NNGGTAA").get_opcodes()
[('insert', 0, 0, 0, 2), ('equal', 0, 5, 2, 7), ('delete', 5, 7, 7, 7)]
```
`edlib.align` would give:
```
align("NNGGTAA","GGTAAAA",task='path')
{'editDistance': 4, 'alphabetLength': 4, 'locations': [(0, 6)], 'cigar': '2I5=2D'}
```
`I` in cigar means insertion and `D` means deletion, `AA` deletion occurs at the end of the string.

I just want to make sure if this behavior in `levenshtein_editops` is speically designed? For me behaviors in `difflib` and `edlib` make more sence.

BTW, the index of ediops position has changed in #148  but the docstring have not been updated yet:

```
 Examples
    --------
    >>> from rapidfuzz.string_metric import levenshtein_editops
    >>> for tag, src_pos, dest_pos in levenshtein_editops("qabxcd", "abycdf"):
    ...    print(("%7s s1[%d] s2[%d]" % (tag, src_pos, dest_pos)))
     delete s1[1] s2[0]
    replace s1[4] s2[3]
     insert s1[6] s2[6]
```

And in latest version,
```
levenshtein_editops("qabxcd", "abycdf")
[('delete', 0, 0), ('replace', 3, 2), ('insert', 6, 5)]
```

Thanks a lot!

**Comment by maxbachmann** [comment]
> Currently the delete opration in levenshtein_editops would select the leftmost one if there are multiple choices
> Other packages would delete the rightmost two As since GGAA is the longest common substring in a row.
> I just want to make sure if this behavior in levenshtein_editops is speically designed? For me behaviors in difflib and edlib make more sence.

I did not really think about this and just returned any alignment without any specific preference on which alignment is returned. The implementation currently only cares about the following properties:
- as fast as possible (currently O([N/64] * M))
- as memory efficient as possible (currently len(s1) * len(s2) * 3bit)
I did not care about the alignment, since I am not very familiar with this field (I mostly have fun implementing these algorithms with high performance) and so I was not sure which alignment should be preferred.

Edlib uses a rather similar implementation with some improvements, which would be nice to have in RapidFuzz as well. This should:
- slightly reduce the memory consumption to around `len(s1) * len(s2) * 2.5 bit`, but from my understanding could in some optimal cases be reduced to `len(s1) * len(s2) * 1.59 bit`
- improve performance for very long sequences
While doing these improvements I should be able to select the same alignment path as edlib. Note that this will likely not make it into v2.0.0, since I still have a few other things to implement first.

> BTW, the index of ediops position has changed in #148 but the docstring have not been updated yet:

Good catch. I will update the docstring appropriately

**Comment by maxbachmann** [comment]
At least the performance + memory usage improvements are probably interesting for the [dinglehopper](https://github.com/qurator-spk/dinglehopper) project as well.

**Comment by hongduosun** [comment]
The scenario is that my string consists of a prefix (let's say length of 4) and some random sequences, s1/s2 is the prefix of that string,  s2 is kind of like a golden-standart template already known and s1 is the observed prefix in the data.

```
string = "TCTTAGA"

s1 = "TCTT" (observed prefix)
s2 = "ATCT" (template prefix)
```
And the alignment would be:
```
 TCTTAGA
 |||
ATCT
```

 Since the lengths of s1 and s2 are same, the number of insertion and deletion operations to make s1 into s2 are also same. 

The key point is that I have to meanwhile find out how many insertions/deletions are actually occur at the end of s1, because that part is actually belong to the latter random sequences. In the example above, I need to adjust the final T in s1 into the random sequence part.

If delete at the end of s1 is more prefered, I guess I have to additionally check if the deleted sequence is equivalent to delete same number of characters at the end of s1? 

As for the preference of inserting at the end of s1, it's quite simple to count the number of  insertions with index equals to len(s1). But there are also some cases the inserts occur at front positions which is equivalent to insert at the end, I am afraid there is no way to check this? 

As far as I know, in the field of bioinformatics, the operations `edlib` gives is better but I don't know if this is the case for other fields.


Thank you so much for all the great work!

**Comment by maxbachmann** [comment]
> As far as I know, in the field of bioinformatics, the operations edlib gives is better but I don't know if this is the case for other fields.

I looked into the reason for this behavior in RapidFuzz and this is indeed done on purpose right now. Generally both edlib and RapidFuzz will always prefer deletion/insertion over a match while backtracing. The difference in your example occurs due to a specific optimization I use in RapidFuzz. Since the Levenshtein distance is not affected by common prefix/suffix of two sequences, it is possible to remove them in linear time before calculating the Levenshtein distance. I do the same when calculating the editops right now. In your example the two strings have the common suffix "AA". The implementation currently strips this suffix and considers them as "matches". You can see the effect of this behavior when slightly extending your example to:

```
>>> levenshtein_editops("GGTAAAAB","NNGGTAA")
[('insert', 0, 0), ('insert', 0, 1), ('delete', 5, 7), ('delete', 6, 7), ('delete', 7, 7)]
```
which returns the result your expecting. So this specific behavior could be changed by not removing the common suffix beforehand.

Note that only difflib keeps the longest common substring intact (even though it is not based on the Levenshtein distance). e.g. for a common prefix edlib has a similar behavior, where it will not keep the longest common substring intact, since it uses insert/delete at the first place possible while backtracing
```
>>> edlib.align("AAAANNGGTAA","AANNGGTAA", task='path')
{'editDistance': 2, 'alphabetLength': 4, 'locations': [(0, 8)], 'cigar': '2=2I7='}

>>> SequenceMatcher(None, "AANNGGTAA","AAAANNGGTAA").get_opcodes()
[('insert', 0, 0, 0, 2), ('equal', 0, 9, 2, 11)]
```

I do not think I can do much about this. For this specific edge case it would be enough to stop removing the common suffix before calculating the alignment. However this would not help the general case. Is there any reason why this behavior is more problematic when it occurs at the end of the string?

**Comment by hongduosun** [comment]
It's great to know that the common prefix/suffix is trimmed before calculating ediops, it's indeed a good optimization regrading speed. I don't think it's problematic in general cases but just a special preference in my project. 
Maybe I can make some tricks at the end of s1 to obtain the result I expected.

Thanks again for the great work!

**Comment by maxbachmann** [comment]
I just noted this behavior is only true in the current development version of v2.0.0 while the old version still prefers to keep characters instead. So the latest released version would output:
```
>>> levenshtein_editops("GGTAAAAB","NNGGTAA")
[('insert', 0, 0), ('insert', 0, 1), ('delete', 3, 5), ('delete', 4, 5), ('delete', 7, 7)]
```
while the current main branch outputs:
```
>>> levenshtein_editops("GGTAAAAB","NNGGTAA")
[('insert', 0, 0), ('insert', 0, 1), ('delete', 5, 7), ('delete', 6, 7), ('delete', 7, 7)]
```

The other possible improvements I found while inspecting this are tracked in #177 and #178
