### ISSUE TITLE
`extractOne` returns a different distance when `score_cutoff` is provided

### ISSUE THREAD

**Issue by xxyzz** [maxbachmann/rapidfuzz#196]
```python
from rapidfuzz.process import extractOne
extractOne('South Korea', ['North Korea'])                     # ('North Korea', 81.81818181818181, 0)
extractOne('South Korea', ['North Korea'], score_cutoff=85.4)  # None
extractOne('South Korea', ['North Korea'], score_cutoff=85.5)  # ('North Korea', 90.68181818181817, 0)
```

This bug was introduced in v2.0.0

**Comment by maxbachmann** [comment]
Good catch. This is a bug in the Indel distance implementation used by fuzz.WRatio. This is fixed in: https://github.com/maxbachmann/rapidfuzz-cpp/commit/c44c5dc82b15abb65aa20c2c3f23ac52cdd12432 + https://github.com/maxbachmann/RapidFuzz/commit/b7cc7e2e29bf0aa770e5822d4e62500df6f8e00d. I will release a new patch version of RapidFuzz with the fix later today.

**Comment by xxyzz** [comment]
Thanks!
