### ISSUE TITLE
Incorrect perfect `fuzz.partial_ratio` score

### ISSUE THREAD

**Issue by TFiFiE** [maxbachmann/rapidfuzz#257]
```
>>> import rapidfuzz
>>> rapidfuzz.__version__
'2.6.0'
>>> begin = 'a' * 24 + 'ba'
>>> end = 'a' * 8 + 'baaab' + 'a' * 8 + 'ba' + 'b' * 10 + 'abbcb'
>>> s1 = begin + 'c' + end
>>> s2 = begin + 'b' + end
>>> rapidfuzz.fuzz.partial_ratio(s1, s2)
100.0
>>> rapidfuzz.fuzz.partial_ratio(s2, s1)
98.46153846153847
```
`fuzz.partial_ratio` is supposed to be commutative and return a perfect score of **100.0** if and only if one string is a substring of the other.

**Comment by maxbachmann** [comment]
Thanks for reporting. `fuzz.partial_ratio` is not always commutative right now as described in https://github.com/maxbachmann/RapidFuzz/issues/219. However the particular case you did run into is indeed a bug in the current implementation. This is fixed in https://github.com/maxbachmann/RapidFuzz/commit/b36ec678a96f11205972551956d5965df917aca0. I will release a patch version with the fix later today.
