### ISSUE TITLE
Hamming distance not working

### ISSUE THREAD

**Issue by amarseg** [maxbachmann/rapidfuzz#260]
Hi!

First, thanks for all the work put into the library!

I'm having issues with using the functions that calculate the Hamming distance. I get the error 'Sequences are not the same length' even when they are, but only when the dictionary I am querying against has more than 12 values. Unfortunately, my query dictionary has a few million values so I have not been able to use the library. Any idea what could be going on?

Thanks!

**Comment by maxbachmann** [comment]
Generally the hamming distance only allows substitutions. For this reason it will not work for sequences with different lengths.
E.g. `Hamming.distance("test", "teste")` is generally not possible and would throw the exception you are experiencing. There are some implementations which generalize the Hamming distance by allowing Insertion/Deletions after the string end, so e.g, the hamming distance of `test`<->`teste` would be 1. This is currently not done in rapidfuzz even though I would be willing to change this behaviour, since the exception is not really useful for anyone either.

If you experience this for strings of similar length a reproducing example would be helpful so I can look into it.

**Comment by amarseg** [comment]
Here's an example of the error I get, I find it puzzling since the length of the sequences is the same as the query. This would give me the 'Sequence lengths are different error' and I don't really understand why?
```
list_a = ['LRFLEWLL', 'RFLEWLLY', 'VLRFLEWL', 'L***WLLL', 'LL***WLL', 'VLL***WL', 'ILY*WCML', 'LY*WCMLY', 'RILY*WCM', 'ILWW*LLF', 'SILWW*LL', 'LRYFDWLL', 'VLRYFDWL', 'IL*WW*LL', 'L*WW*LLL', 'RIL*WW*L', 'LLWFGELL', 'VLLWFGEL', '*LRLGELS', 'L*LRLGEL', 'LRLGELSL', 'RLGELSLY', 'VL*LRLGE', 'IL**YQLL', 'L**YQLLC', 'RIL**YQL', 'IL**YYFL', 'L**YYFLC', 'RIL**YYF', 'IL**YYFL']

 extract('IL**YYFL', list_a, scorer = Hamming.distance, score_cutoff = 0)
```
<img width="516" alt="image" src="https://user-images.githubusercontent.com/9610221/189097509-4beff8c0-91b9-4ced-a5fd-ef4fe3305784.png">

I find sometimes making the list a bit shorter can help remove the error? Not sure if I am missing something very obvious

**Comment by maxbachmann** [comment]
This appears to be a bug. It appears to occur on one specific element:
```python
process.extract('IL**YYFL', ['*LRLGELS'], scorer = Hamming.distance)
process.extractOne('IL**YYFL', ['*LRLGELS'], scorer = Hamming.distance)
```
both fail
Interesting enough the following works as expected:
```python
>>> process.cdist(['IL**YYFL'], ['*LRLGELS'], scorer = Hamming.distance)
array([[7]], dtype=int32)
>>> Hamming.distance('IL**YYFL', '*LRLGELS')
7
```

**Comment by maxbachmann** [comment]
Ah it is no bug :)
Both `process.extract` and `process.extractOne` preprocess strings by default using `utils.default_process`. This preprocesses strings in the following way:
- replace non alphanumeric characters with whitespace
- lowercase string
- strip whitespaces from start and end of string

In you case this means that `'*LRLGELS'` is preprocessed to `'lrlgels'` which only has length 7 instead of 8, which leads to the ValueError. You can avoid this using:
```
extract('IL**YYFL', list_a, scorer = Hamming.distance, score_cutoff = 0, processor=None)
```

I agree this is very surprising.

It would make sense to improve the exceptions of extract/extractOne/cdist to state on which element the error occured.
