### ISSUE TITLE
ERROR: Could not build wheels for rapidfuzz, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by iNANOV** [maxbachmann/rapidfuzz#348]
# BACKGROUND

I am trying to `pip install openbb` 

# PROBLEM

I get following ERROR:

**Could not build wheels for rapidfuzz, which is required to install pyproject.toml-based projects**

Please note, that I am using rapidfuzz 2.9.0 version, but the issue remains also by using 3.3.1

# My software is 

System Version: macOS 13.6 (22G120)
      Kernel Version: Darwin 22.6.0
      

Python 3.11.4

**Comment by maxbachmann** [comment]
Took me a bit to get down to the bottom of this. The latest versions of openbb do no longer claim support for Python 3.11 since https://github.com/OpenBB-finance/OpenBBTerminal/pull/4695, so `pip install openbb` actually installs openbb version 2.3.1. This old version of openbb did depend on rapidfuzz version 1.9.1 which fails to compile.

So either openbb does not support Python 3.11 or it incorrectly states that it doesn't support it. Either way this is an issue with openbb.

**Comment by iNANOV** [comment]
Thank you very much for your efforts and information.

I will follow your advice.
